### ISSUE TITLE
Block does not pass Goofgle Validation

### ISSUE THREAD

**Issue by scaredda** [donnapep/book-review-block#36]
There's a problem in having the Block pass the Google Structured Data Testing Tool.
The error I get is:
"Thing is not a known valid target type for the itemReviewed property."
I searched the web, and the issue is that "Type" should be set as book and not Thing anymore.

Also, the block generates part of the structured data in the Meta of the page, and part inline in the block itself. This creates confusion when other plugins are also injecting Meta tag (fr example I get the wrong "author".

**Comment by donnapep** [comment]
This was fixed in version 1.3.1.
