### ISSUE TITLE
Can Not Find Block in Gutenberg

### ISSUE THREAD

**Issue by TheJeffr0** [donnapep/book-review-block#4]
I'm testing this block using WordPress 4.9.8 and Gutenberg 3.5.0. With the Book Review plugin activated, I visit the Add New Post screen. When I add a new block, I can't find the Book Review block. I've tried using the block search bar and that doesn't work. Gutenberg and the Book Review block are the only plugins installed on the test site. I'm using the Twenty Seventeen theme.

**Comment by donnapep** [comment]
Is this still a problem for you? I've testing using WordPress 4.9.8 with Gutenberg 3.4.0 and 3.7.0 with the Twenty Seventeen theme, and that works. Do you see any errors in the logs that could be related?

**Comment by TheJeffr0** [comment]
I haven't tried it on newer versions of WordPress or Gutenberg, but I will and I'll let you know.

**Comment by donnapep** [comment]
Closing as stale.
